version: '3.5'

services:
  app:
    image: hanabosocom/php-dev:php-8.3-alpine
    user: ${DEV_UID}:${DEV_GID}
    volumes:
      - ./:/var/www:cached
      - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
    environment:
      - APP_ENV=dev
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
      - COMPOSER_HOME=${HOME}/dev/.composer
      - KERNEL_CLASS=Hanaboso\RestBundleTests\app\Kernel
