version: '3.5'

services:
  app:
    image: hanabosocom/php-dev:php-7.4
    user: ${DEV_UID}:${DEV_GID}
    volumes:
      - ./:/var/www
      - ${SSH_AUTH_SOCK}:${SSH_AUTH}
      - ${HOME}/dev/.composer:${HOME}/dev/.composer
    environment:
      - APP_ENV=dev
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
      - COMPOSER_HOME=${HOME}/dev/.composer
      - KERNEL_CLASS=Hanaboso\RestBundleTests\app\Kernel
